name: Auto Close Issues Between 10PM–12AM (Kolkata)

on:
  schedule:
    # Runs every 10 minutes between 16:30–18:30 UTC on Oct 31 (10PM–12AM IST)
    - cron: '*/10 16-18 31 10 *'
    - cron: '0,10,20,30 18 31 10 *'  # Covers 18:00, 18:10, 18:20, 18:30 UTC
  workflow_dispatch:

jobs:
  close-night-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close issues opened between 10PM–12AM IST
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const now = new Date();
            console.log("Current UTC time:", now.toISOString());

            const { data: issues } = await github.rest.issues.listForRepo({
              ...context.repo,
              state: "open",
              per_page: 100
            });

            if (issues.length === 0) {
              console.log("✅ No open issues to close right now.");
              return;
            }

            for (const issue of issues) {
              if (!issue.pull_request) {
                const createdAt = new Date(issue.created_at);
                const utcHour = createdAt.getUTCHours();
                const utcMinute = createdAt.getUTCMinutes();
                
                // IST = UTC + 5:30
                // 10PM IST (22:00) = 16:30 UTC
                // 12AM IST (00:00) = 18:30 UTC (previous day)
                const totalUTCMinutes = utcHour * 60 + utcMinute;
                
                // Check if created between 16:30 UTC (990 min) and 18:30 UTC (1110 min)
                if (totalUTCMinutes >= 990 && totalUTCMinutes < 1110) {
                  await github.rest.issues.createComment({
                    ...context.repo,
                    issue_number: issue.number,
                    body: "🚫 Issues cannot be created or kept open between **10 PM and 12 AM (Kolkata time)** on 31 Oct 2025 due to event rules."
                  });
                  await github.rest.issues.update({
                    ...context.repo,
                    issue_number: issue.number,
                    state: "closed"
                  });
                  console.log(`Closed issue #${issue.number} (created at ${createdAt.toISOString()})`);
                }
              }
            }
